### ISSUE TITLE
Tensorflow_binding?

### ISSUE THREAD

**Issue by Sundy1219** [HawkAaron/warp-transducer#1]
Hi ,
Do you plan to finish Tensorflow_binding?
Looking forward to your reply

**Comment by HawkAaron** [comment]
Yeah, I'm working on it.

**Comment by Sundy1219** [comment]
Great!!!

**Comment by HawkAaron** [comment]
@Sundy1219 You can test tensorflow_binding now at [add_network](https://github.com/HawkAaron/warp-transducer/tree/add_network) branch. Sorry for the delayed response.

**Comment by Sundy1219** [comment]
I will test soon ,Thank you very much !!!
@HawkAaron

**Comment by rzcwade** [comment]
Hi @Sundy1219 ,

I am also working on TF binding and I am interested in your test. Could you share some of your experiment?
