### ISSUE TITLE
tensorflow binding

### ISSUE THREAD

**Issue by rzcwade** [HawkAaron/warp-transducer#11]
Hi @HawkAaron ,

The tensorflow rnnt_loss takes acts as one of the arguments. According to the description acts is a 4-dims tensor shaped [B,T,U,V] from the output network. I am wondering how you go about transforming both [B, T, V] from the encoder and [B, U] from the decoder  into [B,T,U,V]. Could you give more tips about how you derived [B,T,U,V]?

BTW, I think the description on the repo regarding rnnt_loss tensorflow binding is off (says 3-dims for acts) and also, the test sample in add_network branch is not in synced with master.

Thanks!

**Comment by HawkAaron** [comment]
@rzcwade Refer to Graves paper [sequence transduction with recurrent neural networks](https://arxiv.org/pdf/1211.3711.pdf), euqation 12 defined the pdf, its actually a Cartesian product on dimension T and U.

1. For tensorflow, the implementation is simple:
``` python
acts = tf.expand_dims(transcription_acts, 2)      # [B, T, V] => [B, T, 1, V]
                 + tf.expand_dims(prediction_acts, 1) # [B, U, V] => [B, 1, U, V]
```
where `transcription_acts` is shaped [B, T, V], and `prediction_acts` is shaped [B, U, V].

Then you can do other transforms on `acts`, 
``` python
acts = tf.layers.dense(acts, hidden_dim)
```
2. Actually, the add_network branch is a more efficient implementation version. But it cannot performs any transforms on `acts`, only `transcription_acts` and `prediction_acts` are needed.

**Comment by rzcwade** [comment]
@HawkAaron , thank you for your response. I was confused because in the paper it mentioned about fixed length for input and output vectors, and I was under the impression that you have to somehow design a fixed shape 4-D lattice to fit in both the transcription_acts and prediction_acts. Thank you for clarifying this and it really helps. 

Thanks!
