### ISSUE TITLE
pytorch binding for pytorch 1.0

### ISSUE THREAD

**Issue by ybzhou** [HawkAaron/warp-transducer#13]
The current pytorch binding does not work for pytorch 1.0. Are there any plan to support pytorch 1.0?

**Comment by HawkAaron** [comment]
Currently, it works on PyTorch 0.4.1. 
I will update it to support v1.0 once the stable version released.

**Comment by HawkAaron** [comment]
Hi, 
The binding supports PyTorch 1.0 now.

**Comment by ybzhou** [comment]
Thanks for the update
