### ISSUE TITLE
does this binding support multi-gpus?

### ISSUE THREAD

**Issue by Marcovaldong** [HawkAaron/warp-transducer#18]
When I train the transducer with multi-gpus, there is a error: 

```
File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 99, in certify_inputs
    raise ValueError("Output length mismatch")
ValueError: Output length mismatch
```

It looks like, when the data is splited to two gpus, on one gpu the data will doesn't match this.

**Comment by HawkAaron** [comment]
The feature tensor for each utterances is padded to the same length as the maximum one. If split, the length of some utterances would be less than the current maximum length. 

Let's make a simple example:
Suppose there are 2 utterances, shaped as [10, 40], [5, 40]. Then the feature tensor would be shaped [2, 10, 40]. If split into two gpus, the latter would be shaped [1, 10, 40], but actually it only has 5 frames, so the length, 5, is mismatched with the frame 10.

Please don't use PyTorch's DataParallel，try other tools like [horovod](https://github.com/horovod/horovod) or [apex](https://github.com/NVIDIA/apex).

**Comment by Marcovaldong** [comment]
@HawkAaron Thanks for your reply, I'll another two methods.
