### ISSUE TITLE
unable to run test.py file 

### ISSUE THREAD

**Issue by rajeevbaalwan** [HawkAaron/warp-transducer#26]
Even After properly doing make unable to run test.py file:
getting this stacktrace

Traceback (most recent call last):
  File "/home/rajeev/pb/ds3/libs/warp-transducer/pytorch_binding/test/test.py", line 17, in <module>
    from warprnnt_pytorch import RNNTLoss
ModuleNotFoundError: No module named 'warprnnt_pytorch

Any help on this??

**Comment by rajeevbaalwan** [comment]
getting this stacktrace when doing python setup.py install:


running install
running bdist_egg
running egg_info
creating warprnnt_pytorch.egg-info
writing warprnnt_pytorch.egg-info/PKG-INFO
writing dependency_links to warprnnt_pytorch.egg-info/dependency_links.txt
writing top-level names to warprnnt_pytorch.egg-info/top_level.txt
writing manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
reading manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
writing manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/warprnnt_pytorch
copying warprnnt_pytorch/__init__.py -> build/lib.linux-x86_64-3.6/warprnnt_pytorch
running build_ext
building 'warprnnt_pytorch.warp_rnnt' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/rajeev/pb/ds3/libs/warp-transducer/include -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/THC -I/home/rajeev/environments/ds3/include -I/usr/include/python3.6m -c src/binding.cpp -o build/temp.linux-x86_64-3.6/src/binding.o -std=c++11 -fPIC -DWARPRNNT_ENABLE_GPU -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=warp_rnnt -D_GLIBCXX_USE_CXX11_ABI=0
In file included from /home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/THC/THCGeneral.h:12:0,
                 from /home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/THC/THC.h:4,
                 from src/binding.cpp:8:
/home/rajeev/environments/ds3/lib/python3.6/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by zw76859420** [comment]
I have the same problem with you. fatal error: cuda_runtime_api.h: No such file or directory.

**Comment by HawkAaron** [comment]
Please refer to this issue: [fatal error: cuda_runtime_api.h: No such file or directory](https://github.com/HawkAaron/warp-transducer/issues/15)

**Comment by zw76859420** [comment]
It's working! Thank you so much.
