### ISSUE TITLE
GPU Test Failed

### ISSUE THREAD

**Issue by rajeevbaalwan** [HawkAaron/warp-transducer#28]
getting test.py output as :

[  9.53674316e-07]
CPU Tests passed!
GPU execution requested, but not compiled with GPU support
Traceback (most recent call last):
  File "/home/tanish/multi_gpu_ds3/warp-transducer/pytorch_binding/test/test.py", line 171, in <module>
    small_test()
  File "/home/tanish/multi_gpu_ds3/warp-transducer/pytorch_binding/test/test.py", line 77, in small_test
    "small_test costs mismatch."
AssertionError: small_test costs mismatch.

print(cost-expected_cost) = [-4.49566603]
Also cost is coming to be 0.
Any Help on this ???

**Comment by HawkAaron** [comment]
`GPU execution requested, but not compiled with GPU support.`
This error means the library didn't been compiled with GPU.
Please rebuild the library.

```
rm -rf build/*
cd build; cmake -DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME ..; make -j
cd ../pytorch_binding; python setup.py install
```

**Comment by tanishg98** [comment]
Did what you said, got the right cmake output

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-7.5/bin:/home/tanish/environments/ds3_torch_1.1/bin:/usr/local/cuda-7.5/bin:/home/tanish/bin:/home/tanish/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-8.0/bin:/snap/bin (found version "7.5") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tanish/warp-transducer/build


Still getting cost equal to zero and small cost mismatch

CPU Tests passed!
Traceback (most recent call last):
  File "test.py", line 170, in <module>
    small_test()
  File "test.py", line 76, in small_test
    "small_test costs mismatch."
AssertionError: small_test costs mismatch.

**Comment by HawkAaron** [comment]
@tanishg98 Could you pass the `build/test_gpu`?

**Comment by tanishg98** [comment]
How can I check that?

**Comment by HawkAaron** [comment]
@tanishg98 
```
cd /home/tanish/warp-transducer/build; ./test_gpu
```

**Comment by tanishg98** [comment]
./test_gpu: error while loading shared libraries: libwarprnnt.so: cannot open shared object file: No such file or directory

**Comment by HawkAaron** [comment]
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

**Comment by tanishg98** [comment]
Running gpu tests
finish small_test 0
grad mismatch in options_test expected grad: -0.186844 calculated score: 0 !(-0.186944 < 0 < -0.186744)
grad mismatch in options_test expected grad: -0.062555 calculated score: 0 !(-0.062655 < 0 < -0.062455)
grad mismatch in options_test expected grad: 0.249399 calculated score: 0 !(0.249299 < 0 < 0.249499)
grad mismatch in options_test expected grad: -0.203377 calculated score: 0 !(-0.203477 < 0 < -0.203277)
grad mismatch in options_test expected grad: 0.202399 calculated score: 0 !(0.202299 < 0 < 0.202499)
grad mismatch in options_test expected grad: 0.000977 calculated score: 0 !(0.000877 < 0 < 0.001077)
grad mismatch in options_test expected grad: -0.141016 calculated score: 0 !(-0.141116 < 0 < -0.140916)
grad mismatch in options_test expected grad: 0.079123 calculated score: 0 !(0.079023 < 0 < 0.079223)
grad mismatch in options_test expected grad: 0.061893 calculated score: 0 !(0.061793 < 0 < 0.061993)
grad mismatch in options_test expected grad: -0.011552 calculated score: 0 !(-0.011652 < 0 < -0.011452)
grad mismatch in options_test expected grad: -0.08128 calculated score: 0 !(-0.08138 < 0 < -0.08118)
grad mismatch in options_test expected grad: 0.092832 calculated score: 0 !(0.092732 < 0 < 0.092932)
grad mismatch in options_test expected grad: -0.154257 calculated score: 0 !(-0.154357 < 0 < -0.154157)
grad mismatch in options_test expected grad: 0.229433 calculated score: 0 !(0.229333 < 0 < 0.229533)
grad mismatch in options_test expected grad: -0.075176 calculated score: 0 !(-0.075276 < 0 < -0.075076)
grad mismatch in options_test expected grad: -0.246593 calculated score: 0 !(-0.246693 < 0 < -0.246493)
grad mismatch in options_test expected grad: 0.146405 calculated score: 0 !(0.146305 < 0 < 0.146505)
grad mismatch in options_test expected grad: 0.100188 calculated score: 0 !(0.100088 < 0 < 0.100288)
grad mismatch in options_test expected grad: -0.012918 calculated score: 0 !(-0.013018 < 0 < -0.012818)
grad mismatch in options_test expected grad: -0.061593 calculated score: 0 !(-0.061693 < 0 < -0.061493)
grad mismatch in options_test expected grad: 0.074512 calculated score: 0 !(0.074412 < 0 < 0.074612)
grad mismatch in options_test expected grad: -0.055986 calculated score: 0 !(-0.056086 < 0 < -0.055886)
grad mismatch in options_test expected grad: 0.219831 calculated score: 0 !(0.219731 < 0 < 0.219931)
grad mismatch in options_test expected grad: -0.163845 calculated score: 0 !(-0.163945 < 0 < -0.163745)
grad mismatch in options_test expected grad: -0.497627 calculated score: 0 !(-0.497727 < 0 < -0.497527)
grad mismatch in options_test expected grad: 0.20924 calculated score: 0 !(0.20914 < 0 < 0.20934)
grad mismatch in options_test expected grad: 0.288387 calculated score: 0 !(0.288287 < 0 < 0.288487)
grad mismatch in options_test expected grad: 0.013605 calculated score: 0 !(0.013505 < 0 < 0.013705)
grad mismatch in options_test expected grad: -0.03022 calculated score: 0 !(-0.03032 < 0 < -0.03012)
grad mismatch in options_test expected grad: 0.016615 calculated score: 0 !(0.016515 < 0 < 0.016715)
grad mismatch in options_test expected grad: 0.113925 calculated score: 0 !(0.113825 < 0 < 0.114025)
grad mismatch in options_test expected grad: 0.062781 calculated score: 0 !(0.062681 < 0 < 0.062881)
grad mismatch in options_test expected grad: -0.176706 calculated score: 0 !(-0.176806 < 0 < -0.176606)
grad mismatch in options_test expected grad: -0.667078 calculated score: 0 !(-0.667178 < 0 < -0.666978)
grad mismatch in options_test expected grad: 0.367659 calculated score: 0 !(0.367559 < 0 < 0.367759)
grad mismatch in options_test expected grad: 0.299419 calculated score: 0 !(0.299319 < 0 < 0.299519)
grad mismatch in options_test expected grad: -0.356344 calculated score: 0 !(-0.356444 < 0 < -0.356244)
grad mismatch in options_test expected grad: -0.055347 calculated score: 0 !(-0.055447 < 0 < -0.055247)
grad mismatch in options_test expected grad: 0.411691 calculated score: 0 !(0.411591 < 0 < 0.411791)
grad mismatch in options_test expected grad: -0.096922 calculated score: 0 !(-0.097022 < 0 < -0.096822)
grad mismatch in options_test expected grad: 0.029459 calculated score: 0 !(0.029359 < 0 < 0.029559)
grad mismatch in options_test expected grad: 0.067463 calculated score: 0 !(0.067363 < 0 < 0.067563)
grad mismatch in options_test expected grad: -0.063518 calculated score: 0 !(-0.063618 < 0 < -0.063418)
grad mismatch in options_test expected grad: 0.027654 calculated score: 0 !(0.027554 < 0 < 0.027754)
grad mismatch in options_test expected grad: 0.035863 calculated score: 0 !(0.035763 < 0 < 0.035963)
grad mismatch in options_test expected grad: -0.154499 calculated score: 0 !(-0.154599 < 0 < -0.154399)
grad mismatch in options_test expected grad: -0.073942 calculated score: 0 !(-0.074042 < 0 < -0.073842)
grad mismatch in options_test expected grad: 0.228441 calculated score: 0 !(0.228341 < 0 < 0.228541)
grad mismatch in options_test expected grad: -0.16679 calculated score: 0 !(-0.16689 < 0 < -0.16669)
grad mismatch in options_test expected grad: 0.166878 calculated score: 0 !(0.166778 < 0 < 0.166978)
grad mismatch in options_test expected grad: -0.17237 calculated score: 0 !(-0.17247 < 0 < -0.17227)
grad mismatch in options_test expected grad: 0.105565 calculated score: 0 !(0.105465 < 0 < 0.105665)
grad mismatch in options_test expected grad: 0.066804 calculated score: 0 !(0.066704 < 0 < 0.066904)
grad mismatch in options_test expected grad: 0.023875 calculated score: 0 !(0.023775 < 0 < 0.023975)
grad mismatch in options_test expected grad: -0.118256 calculated score: 0 !(-0.118356 < 0 < -0.118156)
grad mismatch in options_test expected grad: 0.094381 calculated score: 0 !(0.094281 < 0 < 0.094481)
grad mismatch in options_test expected grad: -0.104707 calculated score: 0 !(-0.104807 < 0 < -0.104607)
grad mismatch in options_test expected grad: -0.108934 calculated score: 0 !(-0.109034 < 0 < -0.108834)
grad mismatch in options_test expected grad: 0.213642 calculated score: 0 !(0.213542 < 0 < 0.213742)
grad mismatch in options_test expected grad: -0.369844 calculated score: 0 !(-0.369944 < 0 < -0.369744)
grad mismatch in options_test expected grad: 0.180118 calculated score: 0 !(0.180018 < 0 < 0.180218)
grad mismatch in options_test expected grad: 0.189726 calculated score: 0 !(0.189626 < 0 < 0.189826)
grad mismatch in options_test expected grad: 0.025714 calculated score: 0 !(0.025614 < 0 < 0.025814)
grad mismatch in options_test expected grad: -0.079462 calculated score: 0 !(-0.079562 < 0 < -0.079362)
grad mismatch in options_test expected grad: 0.053748 calculated score: 0 !(0.053648 < 0 < 0.053848)
grad mismatch in options_test expected grad: 0.122328 calculated score: 0 !(0.122228 < 0 < 0.122428)
grad mismatch in options_test expected grad: -0.238789 calculated score: 0 !(-0.238889 < 0 < -0.238689)
grad mismatch in options_test expected grad: 0.11646 calculated score: 0 !(0.11636 < 0 < 0.11656)
grad mismatch in options_test expected grad: -0.598687 calculated score: 0 !(-0.598787 < 0 < -0.598587)
grad mismatch in options_test expected grad: 0.302203 calculated score: 0 !(0.302103 < 0 < 0.302303)
grad mismatch in options_test expected grad: 0.296484 calculated score: 0 !(0.296384 < 0 < 0.296584)
score mismatch in options_test expected score: 4.28065 calculated score: -0 !(4.28055 < -0 < 4.28075)
score mismatch in options_test expected score: 3.93844 calculated score: -0 !(3.93834 < -0 < 3.93854)
finish options_test 0
finish inf_test 0
finished 0
Some or all tests fail

**Comment by HawkAaron** [comment]
@tanishg98 Could you provide more details about your platform?
Like CUDA version, GPU architecture, ...

**Comment by tanishg98** [comment]
Cuda version 9.0
GPU 1080Ti
Thanks for the help!!

**Comment by HawkAaron** [comment]
> Did what you said, got the right cmake output
> 
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Found CUDA: /usr/local/cuda-7.5/bin:/home/tanish/environments/ds3_torch_1.1/bin:/usr/local/cuda-7.5/bin:/home/tanish/bin:/home/tanish/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-8.0/bin:/snap/bin (found version "7.5")
> -- cuda found TRUE
> -- Building shared library with GPU support
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/tanish/warp-transducer/build
> 
> Still getting cost equal to zero and small cost mismatch
> 
> CPU Tests passed!
> Traceback (most recent call last):
> File "test.py", line 170, in 
> small_test()
> File "test.py", line 76, in small_test
> "small_test costs mismatch."
> AssertionError: small_test costs mismatch.

Are you sure CUDA 9.0? In your log, "(found version "7.5")", it seems that you used CUDA 7.5

**Comment by tanishg98** [comment]
Yeah, it was detecting CUDA 7.5, it now works fine on CUDA 9.0
Thanks for your time

**Comment by tanishg98** [comment]
I passed both the CPU and GPU test.But when I integrated it with my model, getting this error
 0%|                                                                                                                                                        | 0/187373 [00:00<?, ?it/s]
//print(cost) --> tensor([-0., -0.])
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    run(config)
  File "train.py", line 147, in run
    run_state = run_epoch(char_to_int_dic, model, optimizer, train_ldr, *run_state)
  File "train.py", line 31, in run_epoch
    loss = model.loss(char_to_int_dic, batch)
  File "/home/tanish/multi_gpu_ds3/speech/models/transducer_model.py", line 76, in loss
    loss = loss_fn(out, y, x_lens, y_lens)
  File "/home/tanish/environments/ds3_torch_1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tanish/environments/ds3_torch_1.1/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 100, in forward
    return self.loss(acts, labels, act_lens, label_lens, self.blank, self.reduction)
  File "/home/tanish/environments/ds3_torch_1.1/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 40, in forward
    grads /= minibatch_size
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by xqq2018rebuild** [comment]
@tanishg98 
I meet the same problem with you.When I integrated it with my model, getting this error 
grads /= minibatch_size
RuntimeError: CUDA error: an illegal memory access was encountered
Have you solved the problem?

**Comment by xqq2018rebuild** [comment]
@tanishg98 
git checkout 90fd2b06af1bc1e61083f215877fa5a9eb4976e9 
pytorch_version== 0.4.1
CUDA==9.0
gcc_version==4.9.2
The problem "RuntimeError: CUDA error: an illegal memory access was encountered" can be solved.

CPU Tests passed!
GPU Tests passed!

**Comment by HawkAaron** [comment]
@tanishg98   @xqq2018rebuild  Which version of PyTorch did you use when encountering this error?

**Comment by xqq2018rebuild** [comment]
@HawkAaron 
I used pytorch==0.4.1 CUDA==9.0 gcc == 4.9.2
But modify the latset warp-transducer/pytorch_binding/src  according to jnishi/warp-ctc/pytorch_bingding/src. 
Code as follows:
binding.cpp
**************************************************
int gpu_rnnt(THCudaTensor *acts,
                     **THIntTensor *labels,**
                      **THIntTensor *input_lengths,**
                      **THIntTensor *label_lengths,**
                      THFloatTensor *costs,
                      THCudaTensor *grads,
                      int blank_label,
                      int num_threads);

Modify the relevant code in test/test.py src/gpu_binding.h src/cpu_binding.h .
****************************************************
This will cause the problem.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
THCudaCheck FAIL file=/pytorch/aten/src/ATen/native/cuda/SoftMax.cu line=572 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "test/test.py", line 171, in <module>
    small_test()
  File "test/test.py", line 61, in small_test
    cost, grads = wrap_and_call(acts, labels)
  File "test/test.py", line 47, in wrap_and_call
    cost.backward()
  File "/home/xuqingqing/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/xuqingqing/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/ATen/native/cuda/SoftMax.cu:572

**Comment by gccyxy** [comment]
Hello ,I have met a mistake which is :
from src/binding.cpp:8:
/root/anaconda3/lib/python3.7/site-packages/torch/include/c10/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>

how can I  solve it ??  thanks a lot

**Comment by HawkAaron** [comment]
@gccyxy 
Please refer to issue https://github.com/HawkAaron/warp-transducer/issues/15

**Comment by gccyxy** [comment]
> ./test_gpu: error while loading shared libraries: libwarprnnt.so: cannot open shared object file: No such file or directory

hello， I have 

> ./test_gpu: error while loading shared libraries: libwarprnnt.so: cannot open shared object file: No such file or directory

I have met the same mistake, can you tell me how to handle it ??

**Comment by gccyxy** [comment]
> @gccyxy
> Please refer to issue #15

I have tried this issue , but there is still the same mistake. and i dont know how to set the CUDA_HOME :
my cuda.h is on the paths where:

/cm/shared/apps/hwloc/1.11.8/include/hwloc/cuda.h
/cm/shared/apps/tensorflow/1.7.0/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/cm/shared/apps/openmpi/cuda/64/3.0.0/include/openmpi/opal/mca/hwloc/hwloc1117/hwloc/include/hwloc/cuda.h
/cm/shared/apps/hpcx/2.0.0/ompi-v3.0.x/include/openmpi/opal/mca/hwloc/hwloc1117/hwloc/include/hwloc/cuda.h
/cm/shared/apps/cuda91/toolkit/9.1.85/targets/x86_64-linux/include/cuda.h
/home/jupyter/anaconda3/pkgs/pytorch-1.0.1-cuda92py36h65efead_0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h
/home/jupyter/anaconda3/pkgs/tensorflow-base-1.12.0-gpu_py36h8e0ae2d_0/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/jupyter/anaconda3/pkgs/pytorch-1.0.1-cuda100py36he554f03_0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h
/home/jupyter/anaconda3/pkgs/tensorflow-base-1.12.0-gpu_py36had579c0_0/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/jupyter/anaconda3/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/ai18/Gry/darknet/src/cuda.h
/home/ai18/Gry/darknet2/darknet/src/cuda.h
/home/ai18/Gry/naofinal/darknet_nao/src/cuda.h
/home/ai18/Gry/naofinal/darknet_mobilenet-master/src/cuda.h
/home/ai18/Gry/darknet_Mobile/src/cuda.h
/home/ai18/Gry/darknet_nao/src/cuda.h
/home/ai18/Gry/Gry/darknet/src/cuda.h
/home/ai18/Gry/darknet_mobilenet-master/src/cuda.h
/home/qr/miniconda3/pkgs/tensorflow-base-1.14.0-mkl_py37h7ce6ba3_0/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/qr/miniconda3/lib/python3.7/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/wbw/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/cuda.h
/home/lwj/.pyenv/versions/3.5.2/lib/python3.5/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h



how can I select the CUDA_HOME ?  or the mistake is caused by other reasons?   Thanks a lot!

**Comment by gccyxy** [comment]
> export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

I have tried the export ,but it does not work ! How can I solve it?
[root@node01 test]# export LIBRARY_PATH=/home/wx/warp_transducer/build/:$LIBRARY_PATH
(base) [root@node01 test]# export LD_LIBRARY_PATH=/home/wx/warp_transducer/build/:$LD_LIBRARY_PATH

(base) [root@node01 test]# python test.py
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    from warprnnt_pytorch import RNNTLoss
  File "/root/anaconda3/lib/python3.7/site-packages/warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 6, in <module>
    from ._warp_rnnt import *
  File "/root/anaconda3/lib/python3.7/site-packages/warprnnt_pytorch-0.1-py3.7-linux-x86_64.egg/warprnnt_pytorch/_warp_rnnt/__init__.py", line 3, in <module>
    from .__warp_rnnt import lib as _lib, ffi as _ffi
ImportError: libwarprnnt.so: cannot open shared object file: No such file or directory

**Comment by HawkAaron** [comment]
@gccyxy Have you built the library?

**Comment by gccyxy** [comment]
> @gccyxy Have you built the library?

Thanks a lot ! I have made it . And the reason is my cuda have something wrong. When i try another GPU, it does work.
