### ISSUE TITLE
Are you still working on this repo?

### ISSUE THREAD

**Issue by ZhuoranLyu** [HawkAaron/warp-transducer#3]
Hi, I met a problem using pytorch_binding currently. I am using pytorch 0.4.0 with both python 2 and 3. It gives me this error when I run 'from warprnnt_pytorch import RNNTLoss'

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "warprnnt_pytorch/__init__.py", line 8, in <module>
    from ._warp_rnnt import *
  File "warprnnt_pytorch/_warp_rnnt/__init__.py", line 3, in <module>
    from .__warp_rnnt import lib as _lib, ffi as _ffi
ImportError: No module named __warp_rnnt

**Comment by HawkAaron** [comment]
@ZhuoranLyu  Since this binding currently only works for PyTorch 0.3, maybe there are some conflicts with version 0.4.
When version 1.0 released, I'll update this binding asap.

**Comment by ZhuoranLyu** [comment]
@HawkAaron Thank you for ur reply!
