### ISSUE TITLE
 tensorflow binding undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by Slyne** [HawkAaron/warp-transducer#31]
Hi,
I used a docker with pip installed tensorflow1.14, cuda10, python3.5 and nvidia-415 on my desktop and the script passed the test_cpu, test_gpu.
When I ran 
```
python setup.py install
```
and there seemed no error.

However, when I ran 
```
python setup.py test
```
 the error shows that *'tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.5/dist-packages/warprnnt_tensorflow-0.1-py3.5-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE'*

Before running setup.py install, I find that it first has an error like 'fatal error: not found tensorflow/core/kernels/bounds_check.h', so I just change kernels to framework and past the setup install step.

(But on my desktop, which has cuda9 and tensorflow-1.12, there seems no problem at all since bounds_check.h is under kernels/ in tf1.12 source code. I successfully built this on my desktop.)

UPDATE:
Previously I've encountered */usr/bin/ld: cannot find -ltensorflow_framework*. So followed a solution on [warp-ctc](https://github.com/baidu-research/warp-ctc/issues/138), I made a soft-link 
```
ln -s /usr/local/lib/python3.5/dist-packages/tensorflow/libtensorflow_framework.so.1 /usr/local/lib/ibtensorflow_framework.so
```
. Then I encountered the "xxxxx as list() " problem, so I changed the registered op according to [here](https://github.com/baidu-research/warp-ctc/issues/132).Then I encountered _ZTIN10tensorflow8OpKernelE error.

I successfully solved this problem by just 
```
cd  /usr/local/lib/python3.5/dist-packages/tensorflow/; ln -s libtensorflow_framework.so.1 libtensorflow_framework.so
```

After that, if I directly run
 ```
python setup.py test
```
it will encounter '"Registering two gradient with name 'WarpRNNT'!'. 
So to test the test cases, just
```
python tests/test_basic.py
&
python tests/test_warprnnt_op.py
```

**Comment by yjiangling** [comment]
> Hi,
> I used a docker with pip installed tensorflow1.14, cuda10, python3.5 and nvidia-415 on my desktop and the script passed the test_cpu, test_gpu.
> When I ran
> 
> ```
> python setup.py install
> ```
> 
> and there seemed no error.
> 
> However, when I ran
> 
> ```
> python setup.py test
> ```
> 
> the error shows that _'tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.5/dist-packages/warprnnt_tensorflow-0.1-py3.5-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE'_
> 
> Before running setup.py install, I find that it first has an error like 'fatal error: not found tensorflow/core/kernels/bounds_check.h', so I just change kernels to framework and past the setup install step.
> 
> (But on my desktop, which has cuda9 and tensorflow-1.12, there seems no problem at all since bounds_check.h is under kernels/ in tf1.12 source code. I successfully built this on my desktop.)
> 
> UPDATE:
> Previously I've encountered _/usr/bin/ld: cannot find -ltensorflow_framework_. So followed a solution on [warp-ctc](https://github.com/baidu-research/warp-ctc/issues/138), I made a soft-link
> 
> ```
> ln -s /usr/local/lib/python3.5/dist-packages/tensorflow/libtensorflow_framework.so.1 /usr/local/lib/ibtensorflow_framework.so
> ```
> 
> . Then I encountered the "xxxxx as list() " problem, so I changed the registered op according to [here](https://github.com/baidu-research/warp-ctc/issues/132).Then I encountered _ZTIN10tensorflow8OpKernelE error.
> 
> I successfully solved this problem by just
> 
> ```
> cd  /usr/local/lib/python3.5/dist-packages/tensorflow/; ln -s libtensorflow_framework.so.1 libtensorflow_framework.so
> ```
> 
> After that, if I directly run
> 
> ```
> python setup.py test
> ```
> 
> it will encounter '"Registering two gradient with name 'WarpRNNT'!'.
> So to test the test cases, just
> 
> ```
> python tests/test_basic.py
> &
> python tests/test_warprnnt_op.py
> ```

So why the error "KeyError: "Registering two gradient with name 'WarpRNNT' !" will appear when directly run python setup.py test? I still can not find out the reason.
