### ISSUE TITLE
ImportError: libwarprnnt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zw76859420** [HawkAaron/warp-transducer#33]
Thanks for your code!
When I install your project ends and test_cpu(gpu) is ok.
when import wraprnnt_pytorch , i got the errors as folowing:
  ModuleNotFoundError: No module named 'warprnnt_pytorch.warp_rnnt'
 I try many times, and don't knoe how to solve it.

**Comment by HawkAaron** [comment]
Please change to other directories, then import this module.

**Comment by zw76859420** [comment]
Thanks for your kind answer! It's really work.
