### ISSUE TITLE
still pytorch binding GPU test error

### ISSUE THREAD

**Issue by qmpzzpmq** [HawkAaron/warp-transducer#39]
> running install
> running bdist_egg
> running egg_info
> writing warprnnt_pytorch.egg-info/PKG-INFO
> writing dependency_links to warprnnt_pytorch.egg-info/dependency_links.txt
> writing top-level names to warprnnt_pytorch.egg-info/top_level.txt
> reading manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
> writing manifest file 'warprnnt_pytorch.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> building 'warprnnt_pytorch.warp_rnnt' extension
> gcc -pthread -B /data3/tanghaoyu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data3/tanghaoyu/espnet/tools/warp-transducer/include -I/data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include -I/data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/torch/csrc/api/include -I/data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/TH -I/data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/THC -I/data3/tanghaoyu/anaconda3/include/python3.7m -c src/binding.cpp -o build/temp.linux-x86_64-3.7/src/binding.o -std=c++11 -fPIC -DWARPRNNT_ENABLE_GPU -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=warp_rnnt -D_GLIBCXX_USE_CXX11_ABI=0
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/THC/THCGeneral.h:12:0,
>                  from /data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/THC/THC.h:4,
>                  from src/binding.cpp:8:
> /data3/tanghaoyu/espnet/tools/venv/lib/python3.7/site-packages/torch/lib/include/ATen/cuda/CUDAStream.h:6:30: fatal error: cuda_runtime_api.h: No such file or directory
> compilation terminated.
> error: command 'gcc' failed with exit status 1

#15 
read this issue still get problem, my GCC is 5.4 and environment variable is setted as 

> export CUDAROOT=/usr/local/cuda
> export CUDA_HOME=$CUDAROOT
> export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
> export CUDA_PATH=$CUDAROOT
> 
> export PATH=$CUDAROOT/bin:$PATH
> 
> export LD_LIBRARY_PATH=$CUDA_HOME/extras/CUPTI/lib64:$LD_LIBRARY_PATH
> export LIBRARY_PATH=$LIBRARY_PATH:$CUDA_HOME/lib64:$LIBRARY_PATH
> 
> export LD_LIBRARY_PATH="$CUDA_HOME/lib64:$LD_LIBRARY_PATH"
> export CFLAGS="-I/usr/local/cuda/include $CFLAGS"

**Comment by HawkAaron** [comment]
Please make sure cuda_runtime_api.h does in your $CUDA_HOME/include directory.
And please pull this repo, rebuild again.
