### ISSUE TITLE
tensorflow setup on CPU error

### ISSUE THREAD

**Issue by zhoudoufu** [HawkAaron/warp-transducer#47]
@HawkAaron 
Hi , I installed the GPU version successfully with the latest setup.py script, but I got error when installing a cpu version on Mac for warprnnt_tensorflow.kernels. 

```
ld: library not found for -l:libtensorflow_framework.1.dylib
```

I checked this dylib exists in the directory where I installed tensorflow 1.14. I didn't find similar issue on this. Do you have any clue ?

**Comment by NathanHowell** [comment]
@zhoudoufu possibly related to https://github.com/tensorflow/tensorflow/issues/30564, I've hit that issue before too

**Comment by zhoudoufu** [comment]
@NathanHowell  It works, thanks!
A quick ladder from the issue to the fix.  https://github.com/pio-neil/tensorflow/pull/1/files
