### ISSUE TITLE
Error during building warp-transducer: __shfl_down() is not defined

### ISSUE THREAD

**Issue by AbrarAbdulnabi91** [HawkAaron/warp-transducer#48]
I pulled nvcr.io/nvidia/pytorch:19.06-py3 as my working space image. I was facing this error for a while during make in build warp-transducer: ../warp-transducer/src/reduce.co line 32: __shfl_down() is not defined.

I would like to highlight that __shfl_down() is deprecated and deleted from high version device and no more supported; should change to __shfl_down_sync()[Ref. https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-shuffle-functions]
Fix is to change line 32 in src/reduce.co
            shuff = __shfl_down(x, offset);
To
            shuff = __shfl_down_sync(0xFFFFFFFF, x, offset);

Hope this will help others in their build.

**Comment by HawkAaron** [comment]
Thanks!
