### ISSUE TITLE
How can I build the pkg in windows?

### ISSUE THREAD

**Issue by Times125** [HawkAaron/warp-transducer#49]
How can I build the pkg in windows? 
Can you provide a compiled python installation package for tensorflow-gpu 2.0.0rc1?  Just like [warp-rnnt](https://pypi.org/project/warp-rnnt/)
thanks!

**Comment by HawkAaron** [comment]
I'm not working on Windows. I'd suggest you to install anaconda, and manage related tools using conda.

**Comment by Times125** [comment]
> I'm not working on Windows. I'd suggest you to install anaconda, and manage related tools using conda.

fine, I will try it on linux,Thanks
