### ISSUE TITLE
Can blank assign with non-zero?

### ISSUE THREAD

**Issue by yanz0920** [HawkAaron/warp-transducer#53]
hi, when I use the warprnnt_tensorflow.rnnt_loss(), I set the blank_label to vocab_size-1, is it right?

I saw the python interface, and one sentence infer to blank like:
* The label reserved for the blank symbol should be label 0.

And then I check the source code, but there is no constraint on blank...

**Comment by HawkAaron** [comment]
Yeah, you could set blank label to any class index.
