### ISSUE TITLE
question about gradient to last blank transition

### ISSUE THREAD

**Issue by swpd** [HawkAaron/warp-transducer#55]
Hi @HawkAaron ,
according to Eq. (12) from your [note](https://github.com/HawkAaron/warp-transducer/blob/master/docs/rnnt_notes.pdf), the gradient to last blank transition is:
![image](https://user-images.githubusercontent.com/3040031/69514005-d745d880-0f84-11ea-9e4b-a4c51f1eac70.png)

However I found the actual implementations different: 
https://github.com/HawkAaron/warp-transducer/blob/c6d12f9e1562833c2b4e7ad84cb22aa4ba31d18c/include/detail/gpu_rnnt_kernel.h#L161-L165, should it be
```
if (idx == blank_ && t == T-1 && u == U-1) grad -= exp(alphas[col] + logpk - logll[mb]);
```
for line 165?

Correct me if I am wrong. Thank you for this great repo.

**Comment by HawkAaron** [comment]
You are right, thanks very much!
