### ISSUE TITLE
fatal error: tensorflow/core/framework/bounds_check.h: No such file or directory  #include "tensorflow/core/framework/bounds_check.h"

### ISSUE THREAD

**Issue by yjiangling** [HawkAaron/warp-transducer#56]
Hi, I meet the problem of can't find the file of "tensorflow/core/framework/bounds_check.h" at last step? How can I solve it? Where should I put the TensorFlow source? Could U please give me some help? Thanks a lot!

**Comment by zxbyte** [comment]
How did you solve this problem?

**Comment by yjiangling** [comment]
> How did you solve this problem?

Sorry for late reply, It seems that you should download tensorflow source code and copy it to the warp-transducer dir.

**Comment by fangyixiao18** [comment]
I have put tf source code in warp-transducer dir, but it still had this error...............do you know how to solve it?

**Comment by yjiangling** [comment]
> I have put tf source code in warp-transducer dir, but it still had this error...............do you know how to solve it?

You should copy the TensorFlow source code to the folder:  Your Folder/warp-transducer-master/include/

**Comment by zxbyte** [comment]
> > How did you solve this problem?
> 
> Sorry for late reply, It seems that you should download tensorflow source code and copy it to the warp-transducer dir.

现在没在做相关的事情了，谢谢你的回复。

**Comment by fangyixiao18** [comment]
> > I have put tf source code in warp-transducer dir, but it still had this error...............do you know how to solve it?
> 
> You should copy the TensorFlow source code to the folder: Your Folder/warp-transducer-master/include/

it works.. thank you
