### ISSUE TITLE
cmake problem

### ISSUE THREAD

**Issue by yjiangling** [HawkAaron/warp-transducer#58]
Hi, @HawkAaron ,
    According to your instruction, I finished the cmake command. But it seems that the step of Performing Test CMAKE_HAVE_LIBC_PTHREAD not work successfully. Here is the result of my cmake:

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
**-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed**
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-9.0/ (found version "9.0") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/build

When I continue the next step make, the error will occure as below.

[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
/media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/src/rnnt_entrypoint.cu(1): error: this declaration has no storage class or type specifier

/media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/src/rnnt_entrypoint.cu(1): error: expected a ";"

2 errors detected in the compilation of "/tmp/tmpxft_0000bdf9_00000000-13_rnnt_entrypoint.compute_70.cpp1.ii".
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.cmake:279 (message):
  Error generating file
  /media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o

CMakeFiles/warprnnt.dir/build.make:63: recipe for target 'CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o' failed
make[2]: *** [CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/warprnnt.dir/all' failed
make[1]: *** [CMakeFiles/warprnnt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve this problem? Could U please give me some suggestion? Thanks a lot.

**Comment by HawkAaron** [comment]
I use cmake=3.14.0 and gcc=4.8/5.4, could you have a try?

**Comment by yjiangling** [comment]
> I use cmake=3.14.0 and gcc=4.8/5.4, could you have a try?

OK，thank you. I'm trying to change the version of gcc/g++, hope it will get work.

**Comment by yjiangling** [comment]
> I use cmake=3.14.0 and gcc=4.8/5.4, could you have a try?

Hi @HawkAaron ，
     I finally sovled this problem. But I think it not because the version of gcc/g++. The message occured in cmake step:

**-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed**

turns out to be caused by the version of cmake, I changed the cmake version from 3.15 to 3.14, the cmake process become ok. But the error in make step:

[ 7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
/media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/src/rnnt_entrypoint.cu(1): error: this declaration has no storage class or type specifier

/media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/src/rnnt_entrypoint.cu(1): error: expected a ";"

2 errors detected in the compilation of "/tmp/tmpxft_0000bdf9_00000000-13_rnnt_entrypoint.compute_70.cpp1.ii".
CMake Error at warprnnt_generated_rnnt_entrypoint.cu.o.cmake:279 (message):
Error generating file
/media/huaxin/tcl1/asr/yujiangling/warp-transducer-master/build/CMakeFiles/warprnnt.dir/src/./warprnnt_generated_rnnt_entrypoint.cu.o

CMakeFiles/warprnnt.dir/build.make:63: recipe for target 'CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o' failed
make[2]: *** [CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o] Error 1
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/warprnnt.dir/all' failed
make[1]: *** [CMakeFiles/warprnnt.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

was not caused by gcc/g++ version, it beacuse the file rnnt_entrypoint.cu in src director should be a symlink. I solved it follwed by the instructions given in:
https://github.com/baidu-research/warp-ctc/issues/49

**rm ctc_entrypoint.cu
ln -s ctc_entrypoint.cpp ctc_entrypoint.cu**

Hope it will help others. Thanks a lot!

**Comment by yjiangling** [comment]
@liuyukun98 Thanks a lot. Yes, I also solve it by make a symlink for ctc_entrypoint.cu file. Sorry forget to close that question in #37.
