### ISSUE TITLE
cant find file "tensorflow/core/framework/op.h

### ISSUE THREAD

**Issue by ybNo1** [HawkAaron/warp-transducer#62]
Hi, HawkAaron
I have a problem when running final step installing warp-transducer,
Here's ERROR LOG when running python setup.py install :
`
$ CUDA_HOME=/home/share/cuda10 python setup.py install

setup.py:63: UserWarning: Assuming tensorflow was compiled without C++11 ABI. It is generally true if you are using binary pip package. If you compiled tensorflow from source with gcc >= 5 and didn't set -D_GLIBCXX_USE_CXX11_ABI=0 during compilation, you need to set environment variable TF_CXX11_ABI=1 when compiling this bindings. Also be sure to touch some files in src to trigger recompilation. Also, you need to set (or unsed) this environment variable if getting undefined symbol: _ZN10tensorflow... errors
  warnings.warn("Assuming tensorflow was compiled without C++11 ABI. "
running install
running bdist_egg
running egg_info
writing warprnnt_tensorflow.egg-info/PKG-INFO
writing dependency_links to warprnnt_tensorflow.egg-info/dependency_links.txt
writing top-level names to warprnnt_tensorflow.egg-info/top_level.txt
reading manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
writing manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'warprnnt_tensorflow.kernels' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core -I/home/bin.yang02/program/rnnt-speech-recognition/warp-transducer/tensorflow_binding/../include -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include/external/nsync/public -I/home/share/cuda10/include -I/home/bin.yang02/program/rnnt-speech-recognition/warp-transducer/tensorflow_binding/include -I/home/bin.yang02/envs/pyRNNT/include -I/usr/include/python3.6m -c src/warprnnt_op.cc -o build/temp.linux-x86_64-3.6/src/warprnnt_op.o -std=c++11 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-return-type -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0 -DWARPRNNT_ENABLE_GPU
src/warprnnt_op.cc:6:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
                                          ^
compilation terminated.
error: command 'gcc' failed with exit status 1
`

My tensorflow2.0.1 was installed in pyenv/lib64/python3.6/site-packages/, but I found tensorflow/core/framework/op.h under the pyenv/lib/python3.6/site-packages/tensorflow_core dir.
How to sovle the problem?

**Comment by HawkAaron** [comment]
Please change `tensorflow/core/framework/op.h` with your current file `tensorflow_core/op.h`.

**Comment by yjiangling** [comment]
> Hi, HawkAaron
> I have a problem when running final step installing warp-transducer,
> Here's ERROR LOG when running python setup.py install :
> `
> $ CUDA_HOME=/home/share/cuda10 python setup.py install
> 
> setup.py:63: UserWarning: Assuming tensorflow was compiled without C++11 ABI. It is generally true if you are using binary pip package. If you compiled tensorflow from source with gcc >= 5 and didn't set -D_GLIBCXX_USE_CXX11_ABI=0 during compilation, you need to set environment variable TF_CXX11_ABI=1 when compiling this bindings. Also be sure to touch some files in src to trigger recompilation. Also, you need to set (or unsed) this environment variable if getting undefined symbol: _ZN10tensorflow... errors
> warnings.warn("Assuming tensorflow was compiled without C++11 ABI. "
> running install
> running bdist_egg
> running egg_info
> writing warprnnt_tensorflow.egg-info/PKG-INFO
> writing dependency_links to warprnnt_tensorflow.egg-info/dependency_links.txt
> writing top-level names to warprnnt_tensorflow.egg-info/top_level.txt
> reading manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
> writing manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> running build_ext
> building 'warprnnt_tensorflow.kernels' extension
> gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core -I/home/bin.yang02/program/rnnt-speech-recognition/warp-transducer/tensorflow_binding/../include -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include/external/nsync/public -I/home/share/cuda10/include -I/home/bin.yang02/program/rnnt-speech-recognition/warp-transducer/tensorflow_binding/include -I/home/bin.yang02/envs/pyRNNT/include -I/usr/include/python3.6m -c src/warprnnt_op.cc -o build/temp.linux-x86_64-3.6/src/warprnnt_op.o -std=c++11 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-return-type -I/home/bin.yang02/envs/pyRNNT/lib64/python3.6/site-packages/tensorflow_core/include -D_GLIBCXX_USE_CXX11_ABI=0 -DWARPRNNT_ENABLE_GPU
> src/warprnnt_op.cc:6:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
> #include "tensorflow/core/framework/op.h"
> ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1
> `
> 
> My tensorflow2.0.1 was installed in pyenv/lib64/python3.6/site-packages/, but I found tensorflow/core/framework/op.h under the pyenv/lib/python3.6/site-packages/tensorflow_core dir.
> How to sovle the problem?

You should download tensorflow source code and copy it to the folder: warp-transducer-master/include

**Comment by ybNo1** [comment]
thanks for the reply,  I've solved the problem by making a soft of tf source code link to the target dir.
