### ISSUE TITLE
test.py error

### ISSUE THREAD

**Issue by BuaaAlban** [HawkAaron/warp-transducer#63]
(py36) bokangz@xcdl190205:/scratch/workspace/bokangz/project/rnn-transducer-master/warp-transducer-master/pytorch_binding$ python test/test.py
Traceback (most recent call last):
  File "test/test.py", line 17, in <module>
    from warprnnt_pytorch import RNNTLoss
  File "/proj/xcdhdstaff1/bokangz/anaconda3/envs/py36/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 6, in <module>
    from .warp_rnnt import *
ImportError: /proj/xcdhdstaff1/bokangz/anaconda3/envs/py36/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/warp_rnnt.cpython-36m-x86_64-linux-gnu.so
: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv

**Comment by BuaaAlban** [comment]
Besides, I found it works for torch=1.4.0, but failed with torch=1.2.0 and torch-1.1.0

**Comment by BuaaAlban** [comment]
I can run the test in the master/build but failed to binding pytorch, anyone met the same problem ?

**Comment by HawkAaron** [comment]
Please install the pytorch binding with GCC version >= 4.9

**Comment by BuaaAlban** [comment]
> Please install the pytorch binding with GCC version >= 4.9

It is >=4.9, the problem lies on the pytorch version, I should use torch=1.4.0 and the problem solved
