### ISSUE TITLE
cuda runtime error (77) : an illegal memory access was encountered 

### ISSUE THREAD

**Issue by simonwang517** [HawkAaron/warp-transducer#7]
Hello

When I use Pytorch to train a RNN-Transducer model on a big dataset, I encoutered this error randomly.
It means maybe this error occurs at first epoch, maybe after several epochs. I'm sure it's not a problem of my code, because it works well in 100h dataset.

```
Traceback (most recent call last):
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/search/odin/wang/RNNT-Parallel/run_transducer_bmuf.py", line 211, in run
    transcription, prediction, transducer, optimizer, is_training=True, **conf['model_parameter'])
  File "/search/odin/wang/RNNT-Parallel/util/functions.py", line 188, in batch_iterator_transducer
    loss = objective(logits, batch_label, logits_len, label_len)
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 68, in forward
    return self.rnnt(acts, labels, act_lens, label_lens, self.size_average, self.blank_label)
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 33, in forward
    grads = grads / minibatch_size
  File "/search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/torch/tensor.py", line 342, in __div__
    return self.div(other)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
```

I tried to set 

> torch.backends.cudnn.benchmark = False

 and modified batchsize from 16 to 10 or 20, this problem is gone at first, but it wil come back after several epochs.

From the traces information, it seems to about batchsize.
Do you have some idea about this error?

Thank in advance

**Comment by HawkAaron** [comment]
Could you tell which dataset you used or provide more detailed information about your dataset? Something like maximum feature length, label length. And about your GPU device ?

**Comment by simonwang517** [comment]
My dataset is about 1000 hours Chinese Mandarin. I set feature length Threshold as 784 frames and lable length Threshold as 100 which means 100 Chinese Characters in a sequence. And my GPU device is Tesla M40 24GB.
PyTorch version 0.3.1
Cuda 8.0
Cudnn6.0.21

I check this error on google, the principle reason is label index out of class range, but it doesn't suit in my case. Because sometimes it can run through all dataset but sometimes not. 

I thought maybe it's a problem about cudnn, but I'm not sure. 
eg. when I set torch.backends.cudnn.benchmark = True
batchsize 16 always cause this error but batchsize10 and 20 sometimes not.
When I set torch.backends.cudnn.benchmark = False
batchsize 16 works well at first, but after several epoch of all dataset this error comes back again.

**Comment by HawkAaron** [comment]
It seems that you change the code to satisfy bmuf training, the error occurs at "grads / minibatch_size" , maybe gradient didn't synchronized. I didn't test this lib on multi machine environment, I would be appretiate if you fix this problem.

**Comment by simonwang517** [comment]
I‘m afraid it doesn't matter to bmuf training. Because when I ran this script on single GPU with batch16, this error still exist.
```
Traceback (most recent call last):
  File "run_transducer_sub4.py", line 203, in <module>
    transcription, prediction, transducer, optimizer, is_training=True, **conf['model_parameter'])
  File "/search/odin/wangsenmao/RNNT-Parallel/util/functions.py", line 188, in batch_iterator_transducer
    loss = objective(logits, batch_label, logits_len, label_len)
  File "/search/odin/wangsenmao/anaconda2/envs/py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/search/odin/wangsenmao/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 68, in forward
    return self.rnnt(acts, labels, act_lens, label_lens, self.size_average, self.blank_label)
  File "/search/odin/wangsenmao/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py", line 33, in forward
    grads = grads / minibatch_size
  File "/search/odin/wangsenmao/anaconda2/envs/py3/lib/python3.6/site-packages/torch/tensor.py", line 342, in __div__
    return self.div(other)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCTensorMathPairwise.cu:102
```

**Comment by HawkAaron** [comment]
I notice that you use Chinese Character as label unit, so the vocab size should be over thousands, then it could run out of the device memory.

The activation tensor before rnnt loss is shaped (B, T, U, V), the memory cost is B*T*U*V*4.

**Comment by simonwang517** [comment]
Yes, Chinese vocab size is about 6000， that's why I use Tesla P40 24G as GPU device, 
But this error is not OOM, beacause batch size 10 and 20 is work instead of 16.

**Comment by HawkAaron** [comment]
I think this error is OOM in this context. Would you mind trying following ops in pdb using your maximum length config?
```
(pdb) b /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py:33
(pdb) grads  # print grads, should be working, here you can check the gpu memory
(pdb grads.shape # print grads' shape, and canlculate B*T*U*V*4/1024/1024/1024, compare with the gpu memory left
(pdb) grads / minibatch_size # should be oom, since this line of code could new a tensor, this is my fault, I'll change it.
```

Say, if the error occurs again and there is enough gpu memory, then I don't know how to deal with it. Since everything works well in my environment. 

Good luck.

**Comment by HawkAaron** [comment]
By the way, I have updated the pytorch binding to support 0.4.

**Comment by simonwang517** [comment]
Thanks for your advices, and I reproducted this error and tried ops as you suggested, and I got following log.
```
(Pdb)  b /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py:19
Breakpoint 1 at /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py:19
(Pdb) c
> /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py(19)forward()
-> costs = torch.zeros(minibatch_size)
(Pdb) grads

( 0  , 0  ,.,.) = 
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
     ...       ⋱       ...    
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
( 15 , 30 ,.,.) = 
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
     ...       ⋱       ...    
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
   0   0   0  ...    0   0   0
[torch.cuda.FloatTensor of size 16x31x9x4700 (GPU 0)]
(Pdb) acts.shape
torch.Size([16, 31, 9, 4700])
(Pdb) labels.shape
torch.Size([16, 8])
(Pdb) b /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py:29
Breakpoint 2 at /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py:29
(Pdb) c
> /search/odin/wang/anaconda2/envs/py3/lib/python3.6/site-packages/warprnnt_pytorch-0.1-py3.6-linux-x86_64.egg/warprnnt_pytorch/__init__.py(29)forward()
-> costs = torch.FloatTensor([costs.sum()])
(Pdb) grads
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=70 error=77 : an illegal memory access was encountered
*** RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:70
```

So actually, after function 
> loss_func , all the tensor become unreadable(cuda error 77).  At this time ,GPU usage is only 2600 MiB.
by the way, Inscrease the parameters quantities, set torch.backends.cudnn.benchmark = True can reproduct this error more easily and this error usually occurs during training but not immediately.

**Comment by HawkAaron** [comment]
Hi, I recently done some works on CUDA kernels, and found that this may caused by the cuda device mismatching between cuda kernels and cuda tensors. The bug may solved.

Sorry for the late reply.
