### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_30' while execute make

### ISSUE THREAD

**Issue by GGzhangBOY** [HawkAaron/warp-transducer#79]
The enviroument: RTX2070, Driver v450.80.02, and CUDA 11.0, ubuntu 20.04 
I find that the compute capability of my GPU is 7.5, is there any modification in CMakeLists.txt? Can anyone help me out? I am new to DL under Linux enviroument :D

**Comment by magdacisowska** [comment]
just comment out those 3 lines in CMakeLists.txt:
```
# set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_30,code=sm_30 -O2")
# set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_35,code=sm_35")

set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50")
# set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_52,code=sm_52")
```

**Comment by GGzhangBOY** [comment]
> just comment out those 3 lines in CMakeLists.txt:
> 
> ```
> # set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_30,code=sm_30 -O2")
> # set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_35,code=sm_35")
> 
> set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50")
> # set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_52,code=sm_52")
> ```

Thank you!!! Really save my day!!
