### ISSUE TITLE
warp rnnt tensorflow binding issue

### ISSUE THREAD

**Issue by rzcwade** [HawkAaron/warp-transducer#8]
Hi @HawkAaron ,

I was trying to install your RNNT tensorflow binding so that I can use the RNNTLoss function in TensorFlow. I followed your steps and built  libwarprnnt.so first then python setup.py install. When I tried importing the warprnnt_tensorflow to my python environment, I got the following error:

In [1]: import warprnnt_tensorflow
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-eab9f7b41eca> in <module>()
----> 1 import warprnnt_tensorflow

~/warp-transducer/tensorflow_binding/warprnnt_tensorflow/__init__.py in <module>()
      4 
      5 lib_file = imp.find_module('kernels', __path__)[1]
----> 6 _warprnnt = tf.load_op_library(lib_file)
      7 
      8 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     56   """
     57   with errors_impl.raise_exception_on_not_ok_status() as status:
---> 58     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
     59 
     60   op_list_str = py_tf.TF_GetOpList(lib_handle)

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    514             None, None,
    515             compat.as_text(c_api.TF_Message(self.status.status)),
--> 516             c_api.TF_GetCode(self.status.status))
    517     # Delete the underlying status object from memory o

Any idea how to resolve this issue?

Thanks!

**Comment by HawkAaron** [comment]
Could you mind tell me which version of tf and which brach of this repo you used ?
By the way, after run `python setup.py install`,  you need to change dir, like `cd ..`, then `import warprnnt_tensorflow`.

**Comment by rzcwade** [comment]
Hi @HawkAaron ,

Thank you for your response.  Here's my tf version and branch of the repo I am using:

 print(tf.__version__)
1.7.1

 git checkout
Your branch is up-to-date with 'origin/add_network'.


I did import warprnnt_tensorflow in a different directory and still ran into the same error. python tests/test_warprnnt_op.py failed as well:

py36 tensorflow_binding/tests/test_warprnnt_op.py
Traceback (most recent call last):
  File "tensorflow_binding/tests/test_warprnnt_op.py", line 3, in <module>
    from warprnnt_tensorflow import rnnt_loss
  File "/home/zichengr/anaconda3/lib/python3.6/site-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
  File "/home/zichengr/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/zichengr/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/zichengr/anaconda3/lib/python3.6/site-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_


Thanks!

**Comment by HawkAaron** [comment]
I found the same undefined symbol issue in github: https://github.com/openai/blocksparse/issues/7
It seems that you used different ABI info, say, if you compiled tf from source and add `-D_GLIBCXX_USE_CXX11_ABI=0 `, then you need also add this when compiling this repo.
But if you used GCC>=5.0, then the _GLIBCXX_USE_CXX11_ABI=1, so you need to add `-D_GLIBCXX_USE_CXX11_ABI=1` when doing cmake, and change the code in
https://github.com/HawkAaron/warp-transducer/blob/add_network/tensorflow_binding/setup.py#L60.

[Please check tf website for more information.](https://www.tensorflow.org/install/source#bazel_build)

**Comment by rzcwade** [comment]
Hi @HawkAaron ,

I changed to D_GLIBCXX_USE_CXX11_ABI=1 since I used GCC-5.0 and rebuild it. Now it successfully imported the tensorflow warprnnt! 

Thanks a lot and I really appreciate your help!

Kudos on your amazing work! BTW, have you considered scaling up your MXNet RNN-T and training on a larger data set?

**Comment by HawkAaron** [comment]
Currently I only reproduced the Graves' paper using MXNet binding. It would be easy to train on a larger dataset using your own data processing pipeline, since RNN-T is just a sequence mapping criterion like CTC.

**Comment by alongwithyou** [comment]
@HawkAaron， I use gcc4.8.5 and get the following errors:
Traceback (most recent call last):
  File "warp-transducer/tensorflow_binding/tests/test_warprnnt_op.py", line 3, in <module>
    from warprnnt_tensorflow import rnnt_loss
  File "/NEWAI/Speech/Member/gaoxinglong/bin/anaconda3/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
  File "/NEWAI/Speech/Member/gaoxinglong/bin/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /NEWAI/Speech/Member/gaoxinglong/tools/speech_tools/rnnt-speech-recognition/warp-transducer/build/libwarprnnt.so: undefined symbol: _Z10reduce_expPKfPfiibP11CUstream_st
